name: Deploy
on:
  push:
    branches:
      - master

jobs:
  bump-version:
    name: SemVer Bump
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.bump.outputs.new_version }}
      new_tag: ${{ steps.bump.outputs.new_tag }}
      previous_tag: ${{ steps.bump.outputs.previous_tag }}
      previous_version: ${{ steps.bump.outputs.previous_version }}
      release_type: ${{ steps.bump.outputs.release_type }}
      changelog: ${{ steps.bump.outputs.changelog }}

    steps:
      - uses: actions/checkout@v2
        # Ensure full history is gotten.
        with:
          fetch-depth: 0
      - name: Get New Version
        id: bump
        uses: mathieudutour/github-tag-action@v5.5
        with:
          default_bump: false
          github_token: ${{ secrets.GITHUB_TOKEN }}


  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: bump-version
    if: needs.bump-version.outputs.new_version != null
    steps:
      - uses: actions/checkout@master
      # https://github.com/ansible/pylibssh/blob/1e7b17f/.github/workflows/build-test-n-publish.yml#L146-L151
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Create setuptools_scm env variable
        shell: bash
        run: |
          version=${{ needs.bump-version.outputs.new_version }}
          echo "SETUPTOOLS_SCM_PRETEND_VERSION=$version" >> $GITHUB_ENV
      - name: Install build
        run: |
          python -m pip install build
          python -m pip install setuptools_scm
          python setup.py --version
      - name: Build a binary wheel and a source tarball
        run: python -m build
      - name: Publish distribution ðŸ“¦ to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.pypi_password }}
